import type { ImportTemplateDefinition } from "@/types/import-template";

export const studentImportTemplateDefinition = {
  fileSlug: "students",
  includeInstructions: true,
  importWorksheet: {
    sheetName: "Students",
    fields: [
      {
        key: "lrn",
        canonicalHeader: "LRN",
        displayLabel: "LRN",
        required: true,
        aliases: ["Learner Reference Number"],
        acceptedValues: "12 digits",
        format: "000000000000",
        notes: "Enter the learner's 12-digit LRN.",
      },
      {
        key: "firstName",
        canonicalHeader: "First Name",
        displayLabel: "First Name",
        required: true,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Given name.",
      },
      {
        key: "middleName",
        canonicalHeader: "Middle Name",
        displayLabel: "Middle Name",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional middle name.",
      },
      {
        key: "lastName",
        canonicalHeader: "Last Name",
        displayLabel: "Last Name",
        required: true,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Family name.",
      },
      {
        key: "gender",
        canonicalHeader: "Gender",
        displayLabel: "Gender",
        required: true,
        aliases: [],
        acceptedValues: "MALE, FEMALE",
        format: "Uppercase text",
        notes: "Use MALE or FEMALE.",
      },
      {
        key: "dateOfBirth",
        canonicalHeader: "Date of Birth",
        displayLabel: "Date of Birth",
        required: false,
        aliases: [],
        acceptedValues: "Valid date",
        format: "YYYY-MM-DD",
        notes: "Optional birth date.",
      },
      {
        key: "purok",
        canonicalHeader: "Purok",
        displayLabel: "Purok",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional neighborhood or purok.",
      },
      {
        key: "barangay",
        canonicalHeader: "Barangay",
        displayLabel: "Barangay",
        required: true,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Barangay of residence.",
      },
      {
        key: "municipality",
        canonicalHeader: "Municipality",
        displayLabel: "Municipality",
        required: true,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Municipality or city of residence.",
      },
      {
        key: "province",
        canonicalHeader: "Province",
        displayLabel: "Province",
        required: true,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Province of residence.",
      },
      {
        key: "zipCode",
        canonicalHeader: "Zip Code",
        displayLabel: "Zip Code",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional postal code.",
      },
      {
        key: "fatherName",
        canonicalHeader: "Father Name",
        displayLabel: "Father Name",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional father or parent name.",
      },
      {
        key: "fatherContact",
        canonicalHeader: "Father Contact",
        displayLabel: "Father Contact",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional father or parent contact number.",
      },
      {
        key: "motherName",
        canonicalHeader: "Mother Name",
        displayLabel: "Mother Name",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional mother or parent name.",
      },
      {
        key: "motherContact",
        canonicalHeader: "Mother Contact",
        displayLabel: "Mother Contact",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional mother or parent contact number.",
      },
      {
        key: "guardianName",
        canonicalHeader: "Guardian Name",
        displayLabel: "Guardian Name",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional guardian name.",
      },
      {
        key: "guardianContact",
        canonicalHeader: "Guardian Contact",
        displayLabel: "Guardian Contact",
        required: false,
        aliases: [],
        acceptedValues: "Text",
        format: "Text",
        notes: "Optional guardian contact number.",
      },
    ],
  },
} satisfies ImportTemplateDefinition;
