import { Prisma } from "@/app/generated/prisma/client";
import prisma from "@/lib/prisma";
const select = { id:true, subjectId:true, academicYearId:true, gradeLevel:true, subjectCode:true, subjectDescription:true, deletedAt:true, academicYear:{select:{label:true,status:true}}, terms:{include:{academicTerm:true}} } satisfies Prisma.SubjectOfferingSelect;
export async function findOfferings(q:{academicYearId?:string;gradeLevel?:string}, p:{skip:number;take:number}) { return prisma.subjectOffering.findMany({where:{deletedAt:null,academicYearId:q.academicYearId,gradeLevel:q.gradeLevel},select,skip:p.skip,take:p.take,orderBy:[{academicYear:{startDate:"desc"}},{gradeLevel:"asc"},{subjectCode:"asc"}]}); }
export async function countOfferings(q:{academicYearId?:string;gradeLevel?:string}) { return prisma.subjectOffering.count({where:{deletedAt:null,academicYearId:q.academicYearId,gradeLevel:q.gradeLevel}}); }
export async function findOffering(id:string, tx?:Prisma.TransactionClient) { return (tx??prisma).subjectOffering.findFirst({where:{id,deletedAt:null},select}); }
export async function findOfferingDuplicate(subjectId:string, academicYearId:string, gradeLevel:string, excludeId?:string, tx?:Prisma.TransactionClient) { return (tx??prisma).subjectOffering.findFirst({where:{subjectId,academicYearId,gradeLevel,deletedAt:null,id:excludeId?{not:excludeId}:undefined},select:{id:true}}); }
export async function createOffering(data:Prisma.SubjectOfferingUncheckedCreateInput, termIds:string[], tx:Prisma.TransactionClient) { return tx.subjectOffering.create({data:{...data,terms:{create:termIds.map(academicTermId=>({academicTermId}))}},select}); }
export async function updateOffering(id:string,data:Prisma.SubjectOfferingUncheckedUpdateInput,termIds:string[],tx:Prisma.TransactionClient) { return tx.subjectOffering.update({where:{id},data:{...data,terms:{deleteMany:{},create:termIds.map(academicTermId=>({academicTermId}))}},select}); }
export async function archiveOffering(id:string,tx:Prisma.TransactionClient) { return tx.subjectOffering.update({where:{id},data:{deletedAt:new Date()},select}); }
export async function findOfferingOptions() { return Promise.all([prisma.subject.findMany({where:{deletedAt:null},select:{id:true,code:true,description:true,gradeLevel:true},orderBy:{code:"asc"}}),prisma.academicYear.findMany({where:{status:"ACTIVE"},select:{id:true,label:true,terms:{select:{id:true,name:true,position:true},orderBy:{position:"asc"}}}})]); }
export async function findApprovedRegularJhsOfferings(academicYearId:string, gradeLevel:string, subjectCodes:string[], tx:Prisma.TransactionClient) { return tx.subjectOffering.findMany({where:{academicYearId,gradeLevel,subjectCode:{in:subjectCodes},deletedAt:null},select:{id:true,gradeLevel:true,subjectCode:true,subjectDescription:true,terms:{select:{academicTermId:true},orderBy:{academicTerm:{position:"asc"}}}},orderBy:{subjectCode:"asc"}}); }
