import { Prisma } from "@/app/generated/prisma/client";
import { Permissions, requirePermission } from "@/lib/authorization";
import prisma from "@/lib/prisma";
import { createAuditLogs } from "@/repositories/audit.repository";
import { lockAcademicYearForAcademicTerms } from "@/repositories/academic-year.repository";
import { findAcademicTermsByAcademicYear } from "@/repositories/academic-term.repository";
import { archiveOffering, countOfferings, createOffering, findOffering, findOfferingDuplicate, findOfferingOptions, findOfferings, updateOffering } from "@/repositories/subject-offering.repository";
import { findActiveSubjectById } from "@/repositories/subject.repository";
import type { CreateSubjectOfferingInput, SubjectOfferingTableQuery, UpdateSubjectOfferingInput } from "@/schemas";
export class SubjectOfferingServiceError extends Error {}
function assertActive(year:{status:string}|null) { if (!year || year.status!=="ACTIVE") throw new SubjectOfferingServiceError("Subject offerings can only be changed while their academic year is active."); }
async function validate(values:CreateSubjectOfferingInput|UpdateSubjectOfferingInput,tx:Prisma.TransactionClient,exclude?:string) {
 const [subject,year,terms,duplicate]=await Promise.all([findActiveSubjectById(values.subjectId,tx),lockAcademicYearForAcademicTerms(values.academicYearId,tx),findAcademicTermsByAcademicYear(values.academicYearId,tx),findOfferingDuplicate(values.subjectId,values.academicYearId,values.gradeLevel,exclude,tx)]);
 if(!subject) throw new SubjectOfferingServiceError("Subject not found or archived."); assertActive(year);
 if(subject.gradeLevel!==values.gradeLevel) throw new SubjectOfferingServiceError("Offering grade level must match the Subject grade level.");
 if(duplicate) throw new SubjectOfferingServiceError("An active offering already exists for this subject, academic year, and grade level.");
 if(new Set(values.academicTermIds).size!==values.academicTermIds.length || values.academicTermIds.some(id=>!terms.some(term=>term.id===id))) throw new SubjectOfferingServiceError("Selected terms must belong to the academic year.");
 if(["7","8","9","10"].includes(values.gradeLevel) && (terms.length!==3 || values.academicTermIds.length!==3 || !terms.every(term=>values.academicTermIds.includes(term.id)))) throw new SubjectOfferingServiceError("JHS offerings must apply to all three academic terms.");
 return {subject,year};
}
export async function getSubjectOfferings(query:SubjectOfferingTableQuery) { await requirePermission(Permissions.SUBJECTS); const totalCount=await countOfferings(query); const page=Math.min(query.page,Math.max(1,Math.ceil(totalCount/query.pageSize))); return {items:await findOfferings(query,{skip:(page-1)*query.pageSize,take:query.pageSize}),totalCount,page,pageSize:query.pageSize,pageCount:Math.ceil(totalCount/query.pageSize)}; }
export async function getSubjectOfferingOptions(){await requirePermission(Permissions.SUBJECTS); const [subjects,academicYears]=await findOfferingOptions(); return {subjects,academicYears};}
export async function createSubjectOfferingService(values:CreateSubjectOfferingInput){const session=await requirePermission(Permissions.SUBJECTS);return prisma.$transaction(async tx=>{const {subject,year}=await validate(values,tx);const offering=await createOffering({subjectId:subject.id,academicYearId:year.id,gradeLevel:values.gradeLevel,subjectCode:subject.code,subjectDescription:(subject as {description?:string}).description??subject.code,createdById:session.user.id},values.academicTermIds,tx);await createAuditLogs([{userId:session.user.id,action:"CREATE",module:"SubjectOffering",recordId:offering.id,recordName:`${offering.subjectCode} - ${year.label}`,description:"Created subject offering."}],tx);return offering;});}
export async function updateSubjectOfferingService(id:string,values:UpdateSubjectOfferingInput){const session=await requirePermission(Permissions.SUBJECTS);return prisma.$transaction(async tx=>{const existing=await findOffering(id,tx);if(!existing)throw new SubjectOfferingServiceError("Subject offering not found.");const {subject,year}=await validate(values,tx,id);const offering=await updateOffering(id,{subjectId:subject.id,academicYearId:year.id,gradeLevel:values.gradeLevel,subjectCode:subject.code,subjectDescription:(subject as {description?:string}).description??subject.code},values.academicTermIds,tx);await createAuditLogs([{userId:session.user.id,action:"UPDATE",module:"SubjectOffering",recordId:id,recordName:`${offering.subjectCode} - ${year.label}`,description:"Updated subject offering."}],tx);return offering;});}
export async function archiveSubjectOfferingService(id:string){const session=await requirePermission(Permissions.SUBJECTS);return prisma.$transaction(async tx=>{const offering=await findOffering(id,tx);if(!offering)throw new SubjectOfferingServiceError("Subject offering not found.");assertActive(offering.academicYear);await archiveOffering(id,tx);await createAuditLogs([{userId:session.user.id,action:"ARCHIVE",module:"SubjectOffering",recordId:id,recordName:offering.subjectCode,description:"Archived subject offering."}],tx);return id;});}
